export type StageSource = {
  label: string;
  href: string;
};

export type LearningStage = {
  id: string;
  code: string;
  title: string;
  layer: string;
  theoryTime: string;
  practiceTime: string;
  question: string;
  input: string;
  output: string;
  learn: string;
  concepts: string[];
  theory: {title: string; body: string}[];
  mastery: string[];
  check: string;
  project: string;
  stack: string;
  stackReason: string;
  steps: string[];
  evidence: string[];
  boss: string;
  sources: StageSource[];
  agent: {
    focus: string;
    diagnosis: string;
    nextStep: string;
    prompts: string[];
  };
};

export const learningStages: LearningStage[] = [
  {
    id: "s00",
    code: "S00",
    title: "第一次成功",
    layer: "第一层 · 学会用 AI 构建软件",
    theoryTime: "2–3 小时",
    practiceTime: "半天",
    question: "一个网页怎样从你电脑里的文件，变成别人能访问的网址？",
    input: "一台电脑、可联网环境、你的姓名与一句自我介绍。",
    output: "公开网页、GitHub 仓库，以及一次故障—定位—修复记录。",
    learn: "解释本地文件、浏览器、Git、GitHub、服务器和 URL 的完整链路。",
    concepts: ["文件与文件夹", "HTML / CSS / JavaScript", "浏览器", "终端", "Git", "GitHub", "URL", "HTTP", "部署", "404 / Console"],
    theory: [
      {title: "网页不是一张图片", body: "HTML 描述页面有什么，CSS 决定它长什么样，JavaScript 决定点击后发生什么。浏览器读取这些文件并把它们解释成你看到和操作的页面。"},
      {title: "Git、GitHub 和部署不是一回事", body: "Git 在本地记录版本；GitHub 保存并协作管理仓库；部署平台把某个版本放到公开服务器。少掉任何一层，结果和恢复方式都不同。"},
      {title: "URL 是地址，HTTP 是取东西的规则", body: "浏览器根据 URL 找到服务器，再通过 HTTP 请求资源。404 通常表示路径不存在；Console 报错通常表示页面代码运行时出错。"},
    ],
    mastery: ["能区分语言、工具、平台和运行环境", "能画出本地文件到公开网址的路径", "看到 404 或 Console 报错时知道先检查哪一层"],
    check: "不用术语堆砌，用五句话向朋友解释：为什么 GitHub 仓库存在，不代表网页已经上线？",
    project: "发布一张任何人都能打开的个人介绍网页。",
    stack: "Coding Agent + HTML / CSS / JavaScript + GitHub Pages",
    stackReason: "静态网页变量最少，能在一次任务里看见文件、浏览器、版本和部署的完整因果链。",
    steps: ["创建独立项目文件夹", "用中文描述页面内容和验收条件", "生成并本地预览网页", "完成一次可比较的修改", "提交 Git 并推送 GitHub", "发布公开地址", "制造 404 和脚本错误并恢复"],
    evidence: ["公开网址", "GitHub 仓库", "手机流量访问截图", "修改前后对比", "错误现象、报错文字和修复结果"],
    boss: "亲手制造两个不同层级的错误，并在不重做项目的前提下恢复。",
    sources: [
      {label: "MDN：Web 入门", href: "https://developer.mozilla.org/zh-CN/docs/Learn_web_development/Getting_started"},
      {label: "GitHub Pages 文档", href: "https://docs.github.com/zh/pages"},
    ],
    agent: {
      focus: "建立软件世界最小地图，不让 Agent 接管你的判断。",
      diagnosis: "如果你还分不清 GitHub 和部署，先不要增加框架或数据库。当前最重要的是亲眼看到文件如何经过每一层。",
      nextStep: "先写出网页必须出现的三项内容和公开链接的验收条件，再让 Agent 创建文件。",
      prompts: ["解释 Git 和 GitHub 的区别", "根据报错判断是哪一层", "检查我的发布证据是否完整"],
    },
  },
  {
    id: "s01",
    code: "S01",
    title: "产品问题与 MVP",
    layer: "第一层 · 学会用 AI 构建软件",
    theoryTime: "2–3 小时",
    practiceTime: "1 天",
    question: "为什么很多产品不是做不出来，而是从一开始就做错了问题？",
    input: "一个你反复遇到的问题、现有解决办法和至少一位潜在用户。",
    output: "一页 Product Spec、核心流程、Non-goal 和可验收的 MVP 范围。",
    learn: "判断产品为什么做、第一版做什么和不做什么。",
    concepts: ["用户与场景", "问题证据", "替代方案", "核心任务", "MVP", "Non-goal", "Product Spec", "验收标准", "Backlog"],
    theory: [
      {title: "需求不是一句愿望", body: "“做一个 AI 助手”没有用户、场景和可观察结果。有效问题必须说明谁在什么情况下，正在用什么笨办法，付出了什么代价。"},
      {title: "MVP 是最小验证，不是残缺产品", body: "第一版只保留验证核心假设所需的完整流程。它可以功能少，但用户必须能从输入走到结果，团队也必须能判断假设是否成立。"},
      {title: "Non-goal 是保护交付的边界", body: "把暂时不做的登录、支付、移动端或多 Agent 明确写出来，能阻止 Agent 和团队在实现过程中不断扩张范围。"},
    ],
    mastery: ["能把功能想法改写成问题证据", "能画出一条端到端核心流程", "能写出明确的不做项和验收条件"],
    check: "面对“做一个能帮我工作的 Agent”，至少追问哪五个问题，才能判断第一版应该做什么？",
    project: "把一个模糊想法收敛成可以在一周内验证的产品任务。",
    stack: "访谈记录 + 一页 Product Spec + 纸面流程图",
    stackReason: "问题与范围没有收敛前，写代码只会更快地产生错误资产。",
    steps: ["记录问题发生的真实场景", "列出现有替代方案及其代价", "找到一位潜在用户验证", "写出唯一核心任务", "定义成功证据", "列出至少三个 Non-goal", "把想法整理成一页规格"],
    evidence: ["真实问题记录", "用户原话或行为证据", "核心流程图", "一页 Product Spec", "明确的完成条件"],
    boss: "删除一半想做的功能后，核心假设仍然可以被验证。",
    sources: [
      {label: "Basecamp：Shape Up", href: "https://basecamp.com/shapeup"},
      {label: "GitHub：关于 Issues", href: "https://docs.github.com/zh/issues/tracking-your-work-with-issues/about-issues"},
    ],
    agent: {
      focus: "把“我想做什么”转成“用户为什么需要、怎样证明”。",
      diagnosis: "如果你的描述主要由功能名词组成，说明问题证据仍然不足。Agent 此时应该追问，而不是直接给技术栈。",
      nextStep: "写下最近一次问题发生的时间、人物、现有做法和造成的具体损失。",
      prompts: ["帮我识别伪需求", "把想法压缩成 MVP", "检查我的 Non-goal 是否足够明确"],
    },
  },
  {
    id: "s02",
    code: "S02",
    title: "软件基础",
    layer: "第一层 · 学会用 AI 构建软件",
    theoryTime: "6–8 小时",
    practiceTime: "2–3 天",
    question: "语言、框架、数据库、API 和工具分别位于软件系统的什么位置？",
    input: "S00 的网页和 S01 的一页产品规格。",
    output: "可交互产品壳、系统数据流图和一张技术分类地图。",
    learn: "从用户操作一路解释到页面、服务端、数据库和权限。",
    concepts: ["HTML / CSS / JavaScript", "React / Next.js", "前端 / 后端", "HTTP / API / JSON", "Database / CRUD", "Auth / Authorization", "RLS / Storage"],
    theory: [
      {title: "语言、框架和工具不是同一类东西", body: "JavaScript 是语言；React 是用 JavaScript 构建界面的库；Next.js 是组织前端、服务端和路由的框架；VS Code、Codex 和 Git 是帮助开发的工具。"},
      {title: "前端负责交互，后端负责可信执行", body: "浏览器里的代码可以被用户查看和修改，因此密钥、权限判断和可信数据写入必须放在服务端。前后端通过 HTTP API 交换 JSON。"},
      {title: "认证回答你是谁，授权回答你能做什么", body: "登录成功只证明身份。数据库仍需根据用户身份限制每一行数据；RLS 把这种规则放到数据库层，避免只靠页面隐藏按钮。"},
    ],
    mastery: ["能把常见名词分成语言、框架、服务、工具和协议", "能画出一次按钮点击的数据流", "能解释认证、授权与 RLS 的边界"],
    check: "如果把模型密钥写进前端 JavaScript，会发生什么？为什么登录成功仍不能保证数据安全？",
    project: "为自己的产品搭出输入、处理、结果和失败状态完整的产品壳。",
    stack: "Next.js + TypeScript + 假数据",
    stackReason: "一个项目同时容纳页面与服务端，先用假数据看清系统边界，再连接真实外部服务。",
    steps: ["建立页面与组件", "实现输入和结果状态", "加入空、加载和失败状态", "用假数据跑通核心流程", "画前端—服务端—数据流", "标出密钥和权限边界"],
    evidence: ["可交互产品壳", "四种界面状态", "数据流图", "技术分类图", "一次从页面到服务端的请求记录"],
    boss: "随机抽取十个技术名词，能说出它属于哪一类、在系统哪里、替换它会影响什么。",
    sources: [
      {label: "MDN：Web 开发", href: "https://developer.mozilla.org/zh-CN/docs/Learn_web_development"},
      {label: "Next.js Learn", href: "https://nextjs.org/learn"},
      {label: "Supabase 文档", href: "https://supabase.com/docs"},
    ],
    agent: {
      focus: "补齐系统地图，让你能审查 Agent 生成的技术方案。",
      diagnosis: "如果你只能说“AI 帮我做的”，却无法指出数据经过哪里，下一步应先完成数据流图，而不是继续加功能。",
      nextStep: "选产品中的一个按钮，写出点击前、请求中、成功后、失败后四种状态。",
      prompts: ["判断这些名词属于哪一类", "帮我画一次请求的数据流", "检查密钥和权限应该放在哪里"],
    },
  },
  {
    id: "s03",
    code: "S03",
    title: "AI-Native 开发工作流",
    layer: "第一层 · 学会用 AI 构建软件",
    theoryTime: "4–5 小时",
    practiceTime: "2–3 天",
    question: "怎样让 Coding Agent 持续交付，而不是不断制造不可控修改？",
    input: "一页产品规格、可运行产品壳和 Git 仓库。",
    output: "项目规则、任务卡、小步提交、测试记录和可恢复的 Agent 协作循环。",
    learn: "把 Spec 拆成受控任务，用 Diff、测试和证据判断是否完成。",
    concepts: ["项目上下文", "README / AGENTS", "Plan / Task", "Scope", "Diff", "测试", "Git 快照", "QA", "Skill / Hook", "Agent Loop"],
    theory: [
      {title: "Agent 不知道你脑中的项目", body: "它只能根据当前上下文行动。README 说明项目，AGENTS 约束工作方式，任务卡定义本次边界；缺少这些信息，模型会用自己的假设填空。"},
      {title: "Tool Call 不等于任务完成", body: "模型提出修改只是调用意图；工具执行后还需要检查 Diff、运行程序和验证结果。只有可观察证据通过，才能称为完成。"},
      {title: "小步提交是一种风险控制", body: "把任务缩小到可审查、可测试、可回滚的范围。每个稳定状态形成 Git 快照，失败时回到最后稳定版本，而不是继续在坏状态上堆补丁。"},
    ],
    mastery: ["能写出有边界的任务卡", "能读 Diff 判断修改范围", "能区分 Agent 声称完成和证据证明完成"],
    check: "Agent 回答“已经修复”后，你至少需要检查哪四类证据？",
    project: "用同一套受控循环完成三个小功能，并成功回滚一次错误修改。",
    stack: "Coding Agent + AGENTS.md + Git + 自动检查",
    stackReason: "目标不是学会某个聊天技巧，而是建立可以重复使用的交付控制面。",
    steps: ["补全 README 和项目规则", "把功能拆成单一任务卡", "让 Agent 先计划再修改", "审查文件范围和 Diff", "运行构建与关键流程", "提交稳定快照", "故意制造越界任务并阻止"],
    evidence: ["项目规则文件", "三张任务卡", "三次小步提交", "一次回滚记录", "Agent 声明与实际证据对照"],
    boss: "Agent 故意修改任务范围外的文件，你能发现、拒绝并恢复。",
    sources: [
      {label: "GitHub：查看提交差异", href: "https://docs.github.com/zh/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits"},
      {label: "Anthropic：Building Effective Agents", href: "https://www.anthropic.com/engineering/building-effective-agents"},
    ],
    agent: {
      focus: "把自然语言协作变成可审查、可回滚的工程循环。",
      diagnosis: "如果任务一次修改很多文件又没有验收条件，风险来自任务边界，而不只是模型能力。",
      nextStep: "把当前任务改写为：只改哪些文件、用户能看到什么变化、用什么证据验收。",
      prompts: ["把需求拆成小任务卡", "教我怎么看 Diff", "Agent 说完成后该检查什么"],
    },
  },
  {
    id: "s04",
    code: "S04",
    title: "真实全栈产品",
    layer: "第二层 · 学会构建 AI 产品",
    theoryTime: "6–8 小时",
    practiceTime: "1–2 周",
    question: "一个能注册、保存数据并服务真实用户的产品，还需要哪些系统器官？",
    input: "已验证的 MVP、种子用户和可运行产品壳。",
    output: "带登录、数据库、权限、部署、日志与回滚能力的多用户产品。",
    learn: "解释真实产品的架构、信任边界、生产环境和恢复机制。",
    concepts: ["全栈架构", "Database / Migration / Seed", "Auth / RLS", "Storage", "环境变量", "Preview / Production", "CI/CD", "日志", "备份", "回滚"],
    theory: [
      {title: "真实产品的核心是状态", body: "静态页面只展示文件；真实产品要为不同用户保存、读取和修改状态。数据库结构决定系统记住什么，Migration 决定结构如何安全变化。"},
      {title: "权限必须在可信边界内执行", body: "页面隐藏按钮不能阻止攻击者直接请求接口。服务端和数据库必须验证身份、资源归属和允许的动作。"},
      {title: "上线不是复制文件", body: "Preview 用于验证候选版本，Production 面向真实用户。环境变量、数据库迁移、日志、备份与回滚决定系统出错后能否恢复。"},
    ],
    mastery: ["能画出多用户产品架构图", "能解释数据隔离和信任边界", "能区分 Preview、Production、备份和回滚"],
    check: "账号 B 看不到账号 A 的按钮，为什么仍然必须做接口和数据库层越权测试？",
    project: "上线一个至少三位用户能够注册并完成核心任务的真实产品。",
    stack: "Next.js + Supabase + Vercel",
    stackReason: "用一套可观察服务学习数据库、认证、文件和 RLS，减少自建基础设施带来的无关变量。",
    steps: ["建立数据表与 Migration", "接通注册、登录和退出", "完成 CRUD", "配置 RLS", "用双账号测试隔离", "接入文件存储", "配置 Preview 与 Production", "加入日志、备份和回滚"],
    evidence: ["Production 地址", "架构与信任边界图", "双账号越权测试", "数据库备份", "日志截图", "十分钟回滚记录", "三位用户使用记录"],
    boss: "让第二账号尝试读取和修改第一账号数据，并在发布坏版本后十分钟内恢复。",
    sources: [
      {label: "Next.js：生产部署", href: "https://nextjs.org/docs/app/getting-started/deploying"},
      {label: "Supabase：Row Level Security", href: "https://supabase.com/docs/guides/database/postgres/row-level-security"},
    ],
    agent: {
      focus: "从“页面能跑”升级到“系统可以交给别人使用”。",
      diagnosis: "如果只有一套测试账号或没有回滚记录，当前产品仍缺少真实运行证据。",
      nextStep: "画出用户点击保存后，数据经过页面、服务端、数据库和权限策略的完整路径。",
      prompts: ["检查我的全栈架构", "设计双账号越权测试", "生成上线与回滚清单"],
    },
  },
  {
    id: "s05",
    code: "S05",
    title: "AI 应用基础",
    layer: "第二层 · 学会构建 AI 产品",
    theoryTime: "6–8 小时",
    practiceTime: "3–5 天",
    question: "怎样把不稳定的模型能力，装进一个稳定、可控的软件产品？",
    input: "一个正常软件核心流程、真实输入样例和模型 API。",
    output: "带结构化输出、失败恢复、来源、成本和安全边界的 AI 功能。",
    learn: "处理模型调用、密钥、上下文、知识来源、成本和失败。",
    concepts: ["Model API", "System / User / Context", "Token", "Streaming", "Structured Output", "Provider", "Context Engineering", "Embedding / RAG", "引用", "多模态"],
    theory: [
      {title: "模型能力不是产品能力", body: "模型只根据输入生成概率性结果。产品仍需负责输入限制、上下文选择、输出校验、失败状态、权限、成本和用户能否采取下一步行动。"},
      {title: "结构化输出是模型与软件的合同", body: "自然语言适合人读，JSON 适合程序继续处理。Schema 规定字段和类型，服务端验证后才能让结果进入数据库或触发下一步。"},
      {title: "RAG 不是让模型拥有知识库", body: "系统先检索相关资料，再把选中的内容放进上下文。检索质量、引用和资料新鲜度决定答案能否被追溯。"},
    ],
    mastery: ["能画出一次模型请求与响应", "能设计并验证结构化输出", "能判断何时直接提示、何时需要检索"],
    check: "为什么模型已经支持 JSON 模式，产品仍然必须在服务端校验结果？",
    project: "给 S04 的真实产品增加一个有明确价值的 AI 功能。",
    stack: "服务端模型 API + Structured Output + 可选检索",
    stackReason: "先让 AI 成为正常软件中的受控能力，再考虑更长的自主任务。",
    steps: ["定义 AI 功能输入输出", "准备正常与边界样例", "写 System 指令", "定义 JSON Schema", "服务端调用并校验", "加入超时、重试和失败状态", "记录 Token、延迟与费用", "需要外部知识时加入检索和引用"],
    evidence: ["请求—响应图", "Schema 与校验失败样例", "正常/边界/攻击测试", "成本与延迟记录", "带来源的结果", "AI 失败不破坏核心数据的证明"],
    boss: "模型返回缺字段、错误事实或提示词注入内容时，产品仍保持可恢复。",
    sources: [
      {label: "OpenAI API 指南", href: "https://developers.openai.com/api/docs/guides"},
      {label: "OpenAI Cookbook", href: "https://cookbook.openai.com/"},
      {label: "Anthropic：Context Engineering", href: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"},
    ],
    agent: {
      focus: "判断哪里需要模型，哪里必须保留确定性代码。",
      diagnosis: "如果 AI 输出失败会导致核心数据丢失，说明模型被放在了不该承担的关键路径上。",
      nextStep: "写出 AI 功能的输入 Schema、输出 Schema，以及失败时用户仍能完成什么。",
      prompts: ["帮我定义结构化输出", "判断这里要不要做 RAG", "检查模型失败时产品能否恢复"],
    },
  },
  {
    id: "s06",
    code: "S06",
    title: "Agentic 系统",
    layer: "第二层 · 学会构建 AI 产品",
    theoryTime: "7–9 小时",
    practiceTime: "4–7 天",
    question: "什么是 Agent，Harness 又如何把模型回答变成受控行动？",
    input: "一个需要多步判断、工具调用和反馈循环的开放任务。",
    output: "可观察、可授权、可停止、可回放的最小 Agent 系统。",
    learn: "解释谁决定调用、谁真正执行、谁授权、状态在哪里以及系统为何停止。",
    concepts: ["Model Boundary", "Tool Schema", "Tool Call / Tool Result", "Manual Loop", "Harness", "Runtime", "Permission", "State", "Trace / Replay", "MCP", "Agent SDK"],
    theory: [
      {title: "Agent 是反馈循环，不是更长提示词", body: "模型观察当前状态、选择下一步或工具、获得执行结果，再继续判断，直到完成、失败或触发停止条件。"},
      {title: "Tool Call 不等于 Tool Execution", body: "模型只能生成调用意图。Harness 校验参数、检查权限并把动作交给 Runtime；执行结果再作为 Tool Result 返回模型。"},
      {title: "Harness 是模型外的控制系统", body: "它负责上下文、工具注册、权限、状态、Trace、预算、停止、恢复和人工审批。模型负责判断，但不应自行拥有无限执行权。"},
    ],
    mastery: ["能画出完整 Agent Loop", "能区分模型、Harness、Runtime 和工具", "能设计权限、停止和恢复条件"],
    check: "模型输出了删除文件的 Tool Call，系统中还必须经过哪些环节，文件才真的会被删除？",
    project: "亲手搭建一个只允许有限工具、保留完整 Trace 的白盒 Agent。",
    stack: "Model API + Tool Registry + Manual Loop + Trace",
    stackReason: "先看见每一步再使用高层 SDK，避免把框架魔法误认为 Agent 原理。",
    steps: ["定义任务与停止条件", "声明两个只读工具", "实现 Tool Schema 和执行器", "搭建手动循环", "记录每次模型与工具事件", "加入权限拒绝", "保存状态并从中断处恢复", "用固定任务回放"],
    evidence: ["Agent Loop 图", "Tool Call 与 Tool Result 记录", "权限拒绝证据", "完整 Trace", "中断恢复记录", "固定任务 Replay"],
    boss: "Agent 尝试越权工具、参数错误或无限循环时，Harness 能拒绝、解释并安全停止。",
    sources: [
      {label: "Anthropic：Building Effective Agents", href: "https://www.anthropic.com/engineering/building-effective-agents"},
      {label: "OpenAI：构建 Agent 实用指南", href: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/"},
      {label: "LangGraph：Workflows and Agents", href: "https://docs.langchain.com/oss/python/langgraph/workflows-agents"},
    ],
    agent: {
      focus: "判断任务是否真的需要 Agent，并建立模型外控制面。",
      diagnosis: "如果步骤完全固定，就先做 Workflow；只有下一步需要根据反馈动态判断时，才增加 Agent 循环。",
      nextStep: "把任务分成确定步骤和需要模型判断的步骤，再为每个工具写清权限与副作用。",
      prompts: ["判断该做 Workflow 还是 Agent", "解释 Harness 在哪一层", "检查工具权限与停止条件"],
    },
  },
  {
    id: "s07",
    code: "S07",
    title: "产品载体与系统扩展",
    layer: "第三层 · 扩展产品形态与架构视野",
    theoryTime: "5–7 小时",
    practiceTime: "3–5 天",
    question: "什么时候应该扩展到移动端、本地模型、多 Agent 或长期运行系统？",
    input: "已经验证的产品、真实约束和当前系统瓶颈。",
    output: "一份扩展决策记录和一个经过验证的最小技术实验。",
    learn: "基于场景、隐私、成本、延迟和协作瓶颈接受或拒绝扩展。",
    concepts: ["移动端", "本地 / 开源模型", "Model Card", "Provider 抽象", "Fine-tuning 决策", "Multi-agent", "A2A", "长期 Agent"],
    theory: [
      {title: "载体由使用场景决定", body: "需要相机、定位、推送或离线能力时，移动端才形成硬约束。只因为“想做 App”就迁移技术栈，会增加发布与维护成本。"},
      {title: "本地模型是一组取舍", body: "它可能改善隐私和离线能力，但会引入设备算力、模型体积、更新和质量差异。Model Card 用来理解训练范围、能力和限制。"},
      {title: "多 Agent 解决组织问题，不自动提升智能", body: "只有角色需要不同工具、权限或并行上下文时才值得拆分。否则通信、状态同步和错误归因会比单 Agent 更复杂。"},
    ],
    mastery: ["能为技术扩展写出硬约束", "能比较云模型与本地模型", "能解释多 Agent 增加的协调成本"],
    check: "如果单 Agent 已经能完成任务，拆成三个 Agent 会新增哪些失败点？",
    project: "为现有产品选择一个真实扩展，完成小规模对照实验后决定采用或拒绝。",
    stack: "沿用现有产品 + 单一变量实验",
    stackReason: "一次只改变一个关键变量，才能知道复杂度是否换来了真实收益。",
    steps: ["写出当前瓶颈", "定义扩展必须改善的指标", "选择移动端/本地模型/Provider/多 Agent 之一", "搭最小实验", "记录质量、成本、延迟和维护复杂度", "做采用或拒绝决定"],
    evidence: ["扩展决策记录", "对照实验", "指标变化", "新增风险清单", "采用或拒绝理由"],
    boss: "能够基于证据拒绝一个看起来先进、但没有解决当前硬约束的方案。",
    sources: [
      {label: "Google Cloud：Agentic AI 架构", href: "https://docs.cloud.google.com/architecture/agentic-ai-overview"},
      {label: "Hugging Face：Model Cards", href: "https://huggingface.co/docs/hub/model-cards"},
    ],
    agent: {
      focus: "用约束和证据做扩展决策，而不是追逐新名词。",
      diagnosis: "如果你说不清当前瓶颈，任何扩展都只是增加系统表面积。",
      nextStep: "写出一个必须改善的指标，以及不扩展时无法满足的硬约束。",
      prompts: ["判断是否需要移动端", "比较云模型和本地模型", "判断是否值得做多 Agent"],
    },
  },
  {
    id: "s08",
    code: "S08",
    title: "七类 AI 产品",
    layer: "第三层 · 扩展产品形态与架构视野",
    theoryTime: "7–9 小时",
    practiceTime: "1 周",
    question: "不同 AI 产品真正困难的部分分别是什么？",
    input: "七类参考 Repo、一个目标用户问题和可比较的产品维度。",
    output: "七类产品架构地图，以及一个选定类型的最小产品实验。",
    learn: "识别不同产品在证据、计算、行动、记忆、Runtime 和 Workflow 上的差异。",
    concepts: ["Deep Research", "Data", "Browser", "Coding", "Personal", "Knowledge", "Workflow Automation", "产品架构模式"],
    theory: [
      {title: "七类产品不是七种界面", body: "Deep Research 的核心是来源与综合；Data 产品重计算与可验证结果；Browser 和 Coding 产品重 Runtime、权限和恢复。"},
      {title: "Personal 与 Knowledge 的边界在数据关系", body: "个人助手重长期偏好、任务和隐私；知识产品重资料摄取、检索、引用和更新。二者都需要记忆，但数据生命周期不同。"},
      {title: "Workflow Automation 的价值是可重复执行", body: "它连接触发器、系统和审批，把确定流程自动化；只有无法预先确定下一步时，才在局部引入 Agent。"},
    ],
    mastery: ["能按系统难点而不是界面给产品分类", "能识别每类产品的核心风险", "能从参考 Repo 提取可复用模式而非照抄功能"],
    check: "浏览器 Agent 和 Deep Research 都会访问网页，它们最关键的系统差异是什么？",
    project: "从七类中选择一类，为自己的真实问题做出最小可验证版本。",
    stack: "按类型选择参考 Repo + 默认安全边界",
    stackReason: "先识别产品类型和核心风险，再决定工具与架构，避免把所有问题都做成聊天框。",
    steps: ["用统一维度阅读七类 Repo", "标出输入、状态、工具、证据和失败点", "选择与自己问题最接近的一类", "写最小架构", "完成一条端到端任务", "邀请目标用户验证"],
    evidence: ["七类产品对比表", "参考 Repo 阅读记录", "目标类型架构图", "可运行实验", "用户反馈", "核心风险验证"],
    boss: "给出一个陌生 AI 产品，能在十分钟内判断它属于哪类、核心 Harness 是什么、最危险的失败点在哪里。",
    sources: [
      {label: "Perplexity Search 文档", href: "https://docs.perplexity.ai/docs/search/quickstart"},
      {label: "OpenAI Agents 指南", href: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/"},
      {label: "LangGraph Overview", href: "https://docs.langchain.com/oss/python/langgraph/overview"},
    ],
    agent: {
      focus: "从用户问题识别产品类型，再匹配正确架构模式。",
      diagnosis: "如果方案只是“一个聊天框接模型”，说明尚未识别任务真正需要的证据、工具、状态或 Workflow。",
      nextStep: "选择一条真实任务，写出它需要搜索、计算、行动、记忆和审批中的哪些能力。",
      prompts: ["帮我判断产品属于哪一类", "对比两个参考 Repo", "指出这个产品最大的系统风险"],
    },
  },
  {
    id: "s09",
    code: "S09",
    title: "评测、安全与运营",
    layer: "第四层 · 可靠、可重复地交付",
    theoryTime: "6–8 小时",
    practiceTime: "4–7 天",
    question: "如何证明系统不仅偶尔成功，而是可以交给真实用户？",
    input: "已上线产品、真实 Trace、失败案例和用户反馈。",
    output: "评测集、安全基线、监控指标、故障手册和一次回归报告。",
    learn: "从 Trace、指标和失败集判断系统是否可靠、是否退化。",
    concepts: ["Acceptance", "Golden Dataset", "Evals", "Failure Taxonomy", "LLM-as-Judge", "Trace", "版本", "监控", "Prompt Injection", "PII", "Guardrails", "Incident"],
    theory: [
      {title: "评测从失败定义开始", body: "先定义用户任务和不可接受结果，再收集代表性样例。Golden Dataset 保存固定输入、期望和评分规则，用于比较不同版本。"},
      {title: "LLM-as-Judge 不是事实裁判", body: "模型评审适合规模化判断风格和语义，但需要明确 Rubric、人工校准和偏差检查；权限与安全底线必须用确定性规则兜底。"},
      {title: "运营是持续发现退化", body: "版本、Trace、延迟、费用、错误率和用户反馈要能关联。Incident 记录症状、影响、根因、恢复和预防，避免同类故障重复发生。"},
    ],
    mastery: ["能建立代表性评测集", "能区分确定性检查和模型评审", "能从 Trace 定位失败阶段并建立回归"],
    check: "为什么只看平均得分，可能掩盖一个足以阻止上线的安全失败？",
    project: "为自己的产品建立从验收到线上监控的最小可靠性闭环。",
    stack: "固定任务集 + Trace + 规则检查 + 模型评审 + 监控",
    stackReason: "把主观“感觉更好”变成可重复运行、可比较版本的证据。",
    steps: ["定义任务成功和禁止结果", "收集正常、边界和攻击样例", "建立 Failure Taxonomy", "编写确定性检查", "设计 Judge Rubric 并人工校准", "保存版本与 Trace", "运行基线和候选版本", "建立报警与 Incident 模板"],
    evidence: ["Golden Dataset", "评分 Rubric", "基线报告", "攻击测试", "版本对比", "监控面板", "一次 Incident 或故障演练"],
    boss: "新版本平均分更高但安全样例退化时，能够阻止发布并定位原因。",
    sources: [
      {label: "Anthropic：Agent Evals", href: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"},
      {label: "LangSmith Evaluation", href: "https://docs.langchain.com/langsmith/evaluation"},
      {label: "OWASP：LLM Top 10", href: "https://genai.owasp.org/llm-top-10/"},
    ],
    agent: {
      focus: "把失败变成数据集、规则和可复查的运营闭环。",
      diagnosis: "如果验收只有几个成功截图，当前只能证明系统曾经成功，不能证明它稳定。",
      nextStep: "列出五种不可接受失败，每种准备一个可重复运行的输入样例。",
      prompts: ["帮我建立失败分类", "设计 Golden Dataset", "根据 Trace 判断失败在哪一层"],
    },
  },
  {
    id: "s10",
    code: "S10",
    title: "Starter Kit 与作品集",
    layer: "第四层 · 可靠、可重复地交付",
    theoryTime: "4–5 小时",
    practiceTime: "1–2 周",
    question: "如何证明你掌握的不是一次偶然成功，而是可重复的产品能力？",
    input: "全部项目、提交记录、任务卡、失败记录、用户证据和评测报告。",
    output: "Starter Kit、SOP、第二产品、案例页和完整作品证据链。",
    learn: "判断哪些资产真正可复用，并用公开证据说明自己能再次交付。",
    concepts: ["复用边界", "Starter Kit", "模板", "SOP", "Skill", "AI Usage Report", "用户证据", "案例页", "作品叙事"],
    theory: [
      {title: "复用不是复制旧项目", body: "通用认证、错误状态、日志和发布流程可以进入 Starter Kit；业务字段、历史数据和特定用户假设必须删除或参数化。"},
      {title: "SOP 与 Skill 都需要触发和停止条件", body: "一份可靠流程不仅写步骤，还要说明何时使用、需要什么输入、遇到什么情况停止，以及怎样验证输出。"},
      {title: "作品集卖的是判断证据", body: "案例页要说明问题证据、范围取舍、系统设计、失败与修复、用户结果和下一步，而不是只放漂亮截图。"},
    ],
    mastery: ["能区分通用底座和业务特例", "能让陌生人按说明启动项目", "能用问题、取舍和证据讲清作品价值"],
    check: "为什么一个只能在原电脑运行的模板，不能算 Starter Kit？",
    project: "用自己的 Starter Kit 做出第二个产品，并整理可公开验证的毕业作品。",
    stack: "已验证技术栈 + Starter Kit + SOP + 作品案例页",
    stackReason: "复用价值必须通过新项目、全新环境和陌生人验证，而不是由作者自己宣布。",
    steps: ["复盘全部项目资产", "区分通用与特例", "清理 Starter Kit", "编写安装、上线和排错 SOP", "在全新目录启动", "用它完成第二产品", "比较时间与错误", "整理案例页和 AI Usage Report"],
    evidence: ["Starter Kit 仓库", "三张核心 SOP", "全新环境启动记录", "第二产品", "两次交付对比", "真实用户证据", "公开案例页"],
    boss: "陌生人只看 README，在三十分钟内理解项目并完成核心流程。",
    sources: [
      {label: "GitHub：关于 README", href: "https://docs.github.com/zh/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes"},
      {label: "GitHub：创建模板仓库", href: "https://docs.github.com/zh/repositories/creating-and-managing-repositories/creating-a-template-repository"},
    ],
    agent: {
      focus: "把一次交付沉淀为下一次更快、更可靠的个人生产系统。",
      diagnosis: "如果模板还包含旧业务、密钥或只能在原环境运行，它仍然是旧项目副本。",
      nextStep: "从提交记录中分别找出一项通用代码、一条稳定流程和一个判断标准。",
      prompts: ["判断哪些资产可以复用", "检查 Starter Kit 是否干净", "把项目证据改写成案例叙事"],
    },
  },
];

export const learningLayers = [
  {label: "第一层", title: "学会用 AI 构建软件", range: "S00–S03"},
  {label: "第二层", title: "学会构建 AI 产品", range: "S04–S06"},
  {label: "第三层", title: "扩展产品形态与架构视野", range: "S07–S08"},
  {label: "第四层", title: "可靠、可重复地交付", range: "S09–S10"},
];
